
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/assignment?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
        username: ${dbuser}
        password: ${dbpassword}

    jpa:
        hibernate:
            ddl-auto: create-drop
        